
/* WIP!! */

CREATE TABLE Mgmt.LookUps
( 
	[LOOKUP_ID]                INT IDENTITY ( 1,1 )  NOT NULL ,
	[LOOKUP_NAME]              VARCHAR(50)  NOT NULL ,
	[LOOKUP_RECORD_ID]         INT  NOT NULL ,
	[LOOKUP_VALUE]             VARCHAR(255)  NOT NULL 		DEFAULT  'MISSING',
	IS_CURRENT				   BIT							DEFAULT  1,
	[VERSION_KEY]		       INT NULL						DEFAULT  1,
	[NOTE]				       VARCHAR(768) NULL			DEFAULT  'MISSING', 
	DISPLAY_ORDER		       INT 		NULL, 
	[DB_CREATED_DATE]          DATETIME  NULL    			DEFAULT  NOW(),
	[DB_CREATED_BY]            VARCHAR(255)  NULL			DEFAULT  'MISSING',
	[DB_IS_DELETED]            BIT  NULL 					DEFAULT  'FALSE',
	[DB_LAST_UPDATED_DATE]     DATETIME  NULL 				DEFAULT  NOW(),
	[DB_LAST_UPDATED_BY]       VARCHAR(255)  NULL 			DEFAULT  'MISSING'
	PRIMARY KEY  CLUSTERED ([LOOKUP_ID] ASC)
)
;

END;
