

/* Create Mgmt schema */

CREATE SCHEMA Mgmt
    AUTHORIZATION myuser;




/* Create Organisation Table */

CREATE TABLE Mgmt.Organisation
(
  Organisation_ID 			integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  Company_Name 				varchar(200) DEFAULT 'MISSING' NOT NULL UNIQUE,
  Company_Identifier 		varchar(200) DEFAULT 'MISSING' NOT NULL UNIQUE,
  Parent_Organisation_ID 	integer DEFAULT 1 NOT NULL,
  Inherit_Flg 				boolean DEFAULT FALSE NOT NULL,
  Created_By_User_ID 		bigint DEFAULT 1 NOT NULL,
  Created_Date 				timestamp DEFAULT NOW() NOT NULL,
  Updated_by_User_ID 		bigint DEFAULT 1,
  Updated_Date 				timestamp DEFAULT '9999-12-31 23:59:59' ,
  Is_Skeleton				boolean DEFAULT FALSE NOT NULL,
  DB_Created_Date     		TIMESTAMP WITH TIME ZONE  NULL  DEFAULT  NOW(),
  DB_Created_By        		VARCHAR(255)              NULL	DEFAULT  Current_User,
  DB_Is_Deleted         	BOOLEAN                   NULL 	DEFAULT  FALSE,
  DB_Last_Updated_Date  	TIMESTAMP WITH TIME ZONE  NULL 	DEFAULT  NOW(),
  DB_Last_Updated_By   		VARCHAR(255)              NULL 	DEFAULT  Current_User,
  Constraint "Organisation_ID" PRIMARY KEY (Organisation_ID),
  Foreign Key (Parent_Organisation_ID) References Mgmt.Organisation (Organisation_ID )
)
;

/* Insert the Missing Skeleton as first record*/
INSERT INTO Mgmt.Organisation(company_name, Company_Identifier , inherit_flg, Is_Skeleton	)
	VALUES  ('Missing', 'Missing',   False, True),

/* Insert remaing sekelton records */

	INSERT INTO Mgmt.Organisation(company_name, Company_Identifier , parent_organisation_id, inherit_flg, Is_Skeleton	)
			('Ultimate-Parent', 'Ultimate-Parent',  1, False, True),
	        ('Sub-Co', 'Sub-Co',  2, False, True),
	        ('Public', 'Public',  1, False, True),



COMMENT ON TABLE Mgmt.Organisation IS E'Client organisational structure. \n\nNeeds 3 default skeleton records: \n\n1 = Ultimate Parent \n2 = Sub-Co\n3 = Public\n\nSelf-referencing to allow for a hierarchy to be defined. \n\nInherit_Flg specifies where permissions should be inheritied - i.e. a user with the permissions in #3 will have the same permission in all lower strata of the org. \n\nTherefore there may be 2 parent-child relations coded - where Inherit = True and Inherit = False\n';
COMMENT ON COLUMN Mgmt.Organisation.Inherit_Flg IS E'Default = False - i.e. do NOT inherit';



CREATE TABLE Mgmt.Organisation_History
(
  Organisation_History_ID	bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  Organisation_ID 			integer NOT NULL, 
  Company_Name 				varchar(200) DEFAULT 'MISSING' NOT NULL,
  Company_Identifier 		varchar(200) DEFAULT 'MISSING' NOT NULL,
  Parent_Organisation_ID 	integer DEFAULT 1 NOT NULL,
  Inherit_Flg 				boolean DEFAULT FALSE NOT NULL,
  Created_By_User_ID 		bigint DEFAULT 1 NOT NULL,
  Created_Date 				timestamp DEFAULT NOW() NOT NULL,
  Updated_by_User_ID 		bigint DEFAULT 1,
  Updated_Date 				timestamp DEFAULT '9999-12-31 23:59:59' ,
  DB_Created_Date     		TIMESTAMP WITH TIME ZONE  NULL  DEFAULT  NOW(),
  DB_Created_By        		VARCHAR(255)              NULL	DEFAULT  Current_User,
  DB_Is_Deleted         	BOOLEAN                   NULL 	DEFAULT  FALSE,
  DB_Last_Updated_Date  	TIMESTAMP WITH TIME ZONE  NULL 	DEFAULT  NOW(),
  DB_Last_Updated_By   		VARCHAR(255)              NULL 	DEFAULT  Current_User,
  Constraint "Organisation_History_ID" PRIMARY KEY (Organisation_History_ID),
  Foreign Key (Parent_Organisation_ID) References Mgmt.Organisation (Organisation_ID )
  )
;



CREATE OR REPLACE PROCEDURE Mgmt.sp_AddU_organisation(
  p_company_name varchar,
  p_user_name varchar,
  p_inherit_flg boolean,
  p_company_identifier varchar DEFAULT NULL,
  p_parent_company_name varchar DEFAULT NULL,
  p_update boolean DEFAULT FALSE, -- Set to TRUE to update an existing organisation
  P_is_skeleton boolean DEFAULT FALSE NULL 
)
LANGUAGE plpgsql
AS $BODY$
	DECLARE
	  v_user_id bigint;
	  v_parent_organisation_id integer;
	BEGIN
	  -- Get the user ID
	  SELECT App_User_ID INTO v_user_id
	  FROM Mgmt.App_User
	  WHERE User_Name = p_user_name AND Is_Current = TRUE AND DB_Is_Deleted = FALSE;
	
		  IF NOT FOUND THEN
		    RAISE EXCEPTION 'User % not found', p_user_name;
		  END IF;
	
	  -- Get the parent organisation ID if parent company name is provided
		  	IF p_parent_company_name IS NOT NULL THEN
			    SELECT Organisation_ID INTO v_parent_organisation_id
			    FROM Mgmt.Organisation
			    WHERE Company_Name = p_parent_company_name AND Is_Current = TRUE AND DB_Is_Deleted = FALSE;
		
				    IF NOT FOUND THEN
				      RAISE EXCEPTION 'Parent company % not found', p_parent_company_name;
				    END IF;
	  		ELSE
	    	v_parent_organisation_id := NULL;
	  		END IF;
	
	  -- Check if the company already exists
	  IF EXISTS (SELECT 1 FROM Mgmt.Organisation WHERE Company_Name = p_company_name AND Is_Current = TRUE AND DB_Is_Deleted = FALSE) THEN
	    
				IF p_update THEN
			      
				-- insert history record: 

				INSERT INTO mgmt.organisation_history(
					 	organisation_id, company_name, company_identifier, parent_organisation_id, inherit_flg, created_by_user_id, created_date, updated_by_user_id)
				SELECT 	organisation_id, company_name, company_identifier, parent_organisation_id, inherit_flg, created_by_user_id, created_date, @v_user_id  
				FROM mgmt.organisation	
				Where company_name = p_company_name AND DB_Is_Deleted = FALSE;
				  
				  
				  -- Update existing record:
			      UPDATE Mgmt.Organisation
			      SET 		
							Company_Name = p_company_name,
							Company_Identifier = p_company_identifier,
							Parent_Organisation_ID = v_parent_organisation_id,
							Inherit_Flg = p_inherit_flg, 
							Is_Skeleton = P_is_skeleton,
				  			Updated_Date = NOW(),
			          		Updated_by_User_ID = v_user_id,
			          		DB_Last_Updated_Date = NOW(),
			          		DB_Last_Updated_By = Current_User
			      WHERE Company_Name = p_company_name AND DB_Is_Deleted = FALSE;
			

			    ELSE
			      RAISE NOTICE 'Company % already exists and update is set to FALSE.', p_company_name;
			    END IF;
		
		ELSE
		    -- Insert new record
		    INSERT INTO Mgmt.Organisation (
		      Company_Name,
		      Company_Identifier,
		      Parent_Organisation_ID,
		      Inherit_Flg,
		      Created_By_User_ID	    )
		    VALUES (
		      p_company_name,
		      p_company_identifier,
		      v_parent_organisation_id,
		      p_inherit_flg,
		      v_user_id	    );
	 	END IF;
	END;
$BODY$
;








/* Create App_User Table */

CREATE SEQUENCE Mgmt.seq_App_User_ID
	START WITH 1
	INCREMENT BY 1
	NO MINVALUE
	NO MAXVALUE
	CACHE 1;



CREATE TABLE Mgmt.App_User
(
  App_User_Record_ID bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  App_User_ID bigint NOT NULL DEFAULT nextval('Mgmt.App_User_ID_Seq'),
  User_Name varchar(255) DEFAULT 'MISSING' NOT NULL,
  User_Email varchar(255) DEFAULT 'MISSING' NOT NULL,
  User_Created_Date timestamp DEFAULT NOW() NOT NULL,
  User_Modified_Date timestamp DEFAULT NOW() NOT NULL,
  User_Last_Access_Date timestamp DEFAULT '1999-01-01 00:00:01.000' NULL,
  User_Cred_SO varchar(255) DEFAULT 'MISSING',
  User_Password varchar(768),
  Login_Allowed boolean DEFAULT True,
  Last_Modified_By bigint DEFAULT 1 NOT NULL,
  Is_Current boolean DEFAULT True ,
  DB_Created_Date     	TIMESTAMP WITH TIME ZONE  NULL  DEFAULT  NOW(),
  DB_Created_By        	VARCHAR(255)              NULL	DEFAULT  Current_User,
  DB_Is_Deleted         BOOLEAN                   NULL 	DEFAULT  FALSE,
  DB_Last_Updated_Date  TIMESTAMP WITH TIME ZONE  NULL 	DEFAULT  NOW(),
  DB_Last_Updated_By   	VARCHAR(255)              NULL 	DEFAULT  Current_User,
  Constraint "App_User_ID" PRIMARY KEY (App_User_ID)
)
;


/* Additional Constraints */
CREATE UNIQUE INDEX IX_User_Name_Current on Mgmt.App_User (User_Name) WHERE Is_Current = TRUE;

/* Add Organisation <-> App_User FKs */
ALTER TABLE Mgmt.Organisation ADD CONSTRAINT FK_Organisation__App_User
  FOREIGN KEY (Created_By_User_ID) REFERENCES Mgmt.App_User (App_User_ID);

ALTER TABLE Mgmt.Organisation ADD CONSTRAINT FK_Organisation__App_User2
  FOREIGN KEY (Updated_by_User_ID) REFERENCES Mgmt.App_User (App_User_ID);


/* Comments */
COMMENT ON COLUMN Mgmt.App_User.User_Cred_SO IS E'Used to hold secondary credential ID (but not password) for a secret manager / SSO provider.';
COMMENT ON COLUMN Mgmt.App_User.User_Password IS E'NOT IN USE\nPlaceholder for user passwords if not managed at DB level. Passwords should be salted and hashed on entry.';
COMMENT ON COLUMN Mgmt.App_User.Login_Allowed IS E'NOT IN USE\nCould be used to prevent user login without removing from system. Never remove user ids';
COMMENT ON COLUMN Mgmt.App_User.Last_Modified_By IS E'Captures Users acting on other User accounts - e.g. administrators';


/* Insert Skeleton Admin User */
INSERT INTO Mgmt.App_User	(user_name) 
VALUES ('Administrator1');











