

/* Business Data Catalog */
CREATE TABLE Mgmt.Domain
(
  Domain_ID integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  Domain_Name varchar(200) DEFAULT 'MISSING' NOT NULL,
  Domain_Description varchar(2000) DEFAULT 'MISSING' NOT NULL,
  Created_By_ID bigint DEFAULT 1 NOT NULL,
  Owned_By_ID bigint DEFAULT 1 NOT NULL,
  Created_Date date DEFAULT NOW() NOT NULL,
  DB_Created_Date     	TIMESTAMP WITH TIME ZONE  NULL  DEFAULT  NOW(),
  DB_Created_By        	VARCHAR(255)              NULL	DEFAULT  Current_User,
  DB_Is_Deleted         BOOLEAN                   NULL 	DEFAULT  FALSE,
  DB_Last_Updated_Date  TIMESTAMP WITH TIME ZONE  NULL 	DEFAULT  NOW(),
  DB_Last_Updated_By   	VARCHAR(255)              NULL 	DEFAULT  Current_User,
);

ALTER TABLE Mgmt.Domain ADD CONSTRAINT Domain_ID
  PRIMARY KEY (Domain_ID);


CREATE TABLE Mgmt.Entities
(
  Entity_ID bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  Entity_Name varchar(255) NOT NULL,
  Entity_Description varchar(2000),
  Created_By_ID bigint DEFAULT 1 NOT NULL,
  Created_Date date DEFAULT NOW(),
  Domain_ID integer NOT NULL
);


COMMENT ON TABLE Mgmt.Entities IS E'Entities holds LOGICAL data entities - i.e. tied to business glossaries, not systems. ';

ALTER TABLE Mgmt.Entities ADD CONSTRAINT Entity_Id
  PRIMARY KEY (Entity_ID);

CREATE TABLE Mgmt.Attributes
(
  Attribute_ID bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  Attribute_Name varchar(256) DEFAULT 'MISSING',
  Attribute_Description varchar(2000),
  Created_By_ID bigint DEFAULT 1 NOT NULL,
  Created_Date date DEFAULT NOW(),
  URI varchar(2000) DEFAULT 'MISSING',
  Entity_ID bigint DEFAULT 1 NOT NULL,
  DB_Created_Date     	TIMESTAMP WITH TIME ZONE  NULL  DEFAULT  NOW(),
  DB_Created_By        	VARCHAR(255)              NULL	DEFAULT  Current_User,
  DB_Is_Deleted         BOOLEAN                   NULL 	DEFAULT  FALSE,
  DB_Last_Updated_Date  TIMESTAMP WITH TIME ZONE  NULL 	DEFAULT  NOW(),
  DB_Last_Updated_By   	VARCHAR(255)              NULL 	DEFAULT  Current_User,
)
;


COMMENT ON TABLE Mgmt.Attributes IS E'Captures LOGICAL attributes under logical entities.\nAttributes should be aligned to business glossary rather than source system field/column names. \n'
;
COMMENT ON COLUMN Mgmt.Attributes.URI IS E'External URI for futher information / source of definition';


ALTER TABLE Mgmt.Attributes ADD CONSTRAINT Att_ID
  PRIMARY KEY (Attribute_ID);


ALTER TABLE Mgmt.Attributes ADD CONSTRAINT FK_Attributes__Entities
  FOREIGN KEY (Entity_ID) REFERENCES Mgmt.Entities (Entity_ID);

ALTER TABLE Mgmt.Attributes ADD CONSTRAINT FK_Attributes__Users
  FOREIGN KEY (Created_By_ID) REFERENCES Mgmt.App_User (App_User_ID);
