

/* Create Mgmt schema */

CREATE SCHEMA Mgmt
    AUTHORIZATION myuser;




/* Create Organisation Table */

CREATE TABLE Mgmt.Organisation
(
  Organisation_ID 			integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  Company_Name 				varchar(200) DEFAULT 'MISSING' NOT NULL UNIQUE,
  Company_Identifier 		varchar(200) DEFAULT 'MISSING' NOT NULL UNIQUE,
  Parent_Organisation_ID 	integer DEFAULT 1 NOT NULL,
  Inherit_Flg 				boolean DEFAULT FALSE NOT NULL,
  Created_By_User_ID 		bigint DEFAULT 1 NOT NULL,
  Created_Date 				timestamp DEFAULT NOW() NOT NULL,
  Updated_by_User_ID 		bigint DEFAULT 1,
  Updated_Date 				timestamp DEFAULT '9999-12-31 23:59:59' ,
  Is_Skeleton				boolean DEFAULT FALSE NOT NULL,
  DB_Created_Date     		TIMESTAMP WITH TIME ZONE  NULL  DEFAULT  NOW(),
  DB_Created_By        		VARCHAR(255)              NULL	DEFAULT  Current_User,
  DB_Is_Deleted         	BOOLEAN                   NULL 	DEFAULT  FALSE,
  DB_Last_Updated_Date  	TIMESTAMP WITH TIME ZONE  NULL 	DEFAULT  NOW(),
  DB_Last_Updated_By   		VARCHAR(255)              NULL 	DEFAULT  Current_User,
  Constraint "Organisation_ID" PRIMARY KEY (Organisation_ID),
  Foreign Key (Parent_Organisation_ID) References Mgmt.Organisation (Organisation_ID )
)
;

/* Insert the Missing Skeleton as first record*/
INSERT INTO Mgmt.Organisation(company_name, Company_Identifier , inherit_flg, Is_Skeleton	)
	VALUES  ('Missing', 'Missing',   False, True)
;
/* Insert remaing sekelton records */

	INSERT INTO Mgmt.Organisation(company_name, Company_Identifier , parent_organisation_id, inherit_flg, Is_Skeleton	)
	VALUES 
			('Ultimate-Parent', 'Ultimate-Parent',  1, False, True),
	        ('Sub-Co', 'Sub-Co',  2, False, True),
	        ('Public', 'Public',  1, False, True);


COMMENT ON TABLE Mgmt.Organisation IS E'Client organisational structure. \n\nNeeds 3 default skeleton records: \n\n1 = Ultimate Parent \n2 = Sub-Co\n3 = Public\n\nSelf-referencing to allow for a hierarchy to be defined. \n\nInherit_Flg specifies where permissions should be inheritied - i.e. a user with the permissions in #3 will have the same permission in all lower strata of the org. \n\nTherefore there may be 2 parent-child relations coded - where Inherit = True and Inherit = False\n';
COMMENT ON COLUMN Mgmt.Organisation.Inherit_Flg IS E'Default = False - i.e. do NOT inherit';



CREATE TABLE Mgmt.Organisation_History
(
  Organisation_History_ID	bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  Organisation_ID 			integer NOT NULL, 
  Company_Name 				varchar(200) DEFAULT 'MISSING' NOT NULL,
  Company_Identifier 		varchar(200) DEFAULT 'MISSING' NOT NULL,
  Parent_Organisation_ID 	integer DEFAULT 1 NOT NULL,
  Inherit_Flg 				boolean DEFAULT FALSE NOT NULL,
  Created_By_User_ID 		bigint DEFAULT 1 NOT NULL,
  Created_Date 				timestamp DEFAULT NOW() NOT NULL,
  Updated_by_User_ID 		bigint DEFAULT 1,
  Updated_Date 				timestamp DEFAULT '9999-12-31 23:59:59' ,
  DB_Created_Date     		TIMESTAMP WITH TIME ZONE  NULL  DEFAULT  NOW(),
  DB_Created_By        		VARCHAR(255)              NULL	DEFAULT  Current_User,
  DB_Is_Deleted         	BOOLEAN                   NULL 	DEFAULT  FALSE,
  DB_Last_Updated_Date  	TIMESTAMP WITH TIME ZONE  NULL 	DEFAULT  NOW(),
  DB_Last_Updated_By   		VARCHAR(255)              NULL 	DEFAULT  Current_User,
  Constraint "Organisation_History_ID" PRIMARY KEY (Organisation_History_ID),
  Foreign Key (Parent_Organisation_ID) References Mgmt.Organisation (Organisation_ID )
  )
;



CREATE OR REPLACE PROCEDURE Mgmt.sp_AddU_organisation(
  p_company_name varchar,
  p_user_name varchar,
  p_inherit_flg boolean,
  p_company_identifier varchar DEFAULT NULL,
  p_parent_company_name varchar DEFAULT NULL,
  p_update boolean DEFAULT FALSE, -- Set to TRUE to update an existing organisation
  P_is_skeleton boolean DEFAULT FALSE 
)
LANGUAGE plpgsql
AS $BODY$
	DECLARE
	  v_user_id bigint;
	  v_parent_organisation_id integer;
	BEGIN
	  -- Get the user ID
	  SELECT App_User_ID INTO v_user_id
	  FROM Mgmt.App_User
	  WHERE User_Name = p_user_name AND Is_Current = TRUE AND DB_Is_Deleted = FALSE;
	
		  IF NOT FOUND THEN
		    RAISE EXCEPTION 'User % not found', p_user_name;
		  END IF;
	
	  -- Get the parent organisation ID if parent company name is provided
		  	IF p_parent_company_name IS NOT NULL THEN
			    SELECT Organisation_ID INTO v_parent_organisation_id
			    FROM Mgmt.Organisation
			    WHERE Company_Name = p_parent_company_name AND Is_Current = TRUE AND DB_Is_Deleted = FALSE;
		
				    IF NOT FOUND THEN
				      RAISE EXCEPTION 'Parent company % not found', p_parent_company_name;
				    END IF;
	  		ELSE
	    	v_parent_organisation_id := NULL;
	  		END IF;
	
	  -- Check if the company already exists
	  IF EXISTS (SELECT 1 FROM Mgmt.Organisation WHERE Company_Name = p_company_name AND Is_Current = TRUE AND DB_Is_Deleted = FALSE) THEN
	    
				IF p_update THEN
			      
				-- insert history record: 

				INSERT INTO mgmt.organisation_history(
					 	organisation_id, company_name, company_identifier, parent_organisation_id, inherit_flg, created_by_user_id, created_date, updated_by_user_id)
				SELECT 	organisation_id, company_name, company_identifier, parent_organisation_id, inherit_flg, created_by_user_id, created_date, @v_user_id  
				FROM mgmt.organisation	
				Where company_name = p_company_name AND DB_Is_Deleted = FALSE;
				  
				  
				  -- Update existing record:
			      UPDATE Mgmt.Organisation
			      SET 		
							Company_Name = p_company_name,
							Company_Identifier = p_company_identifier,
							Parent_Organisation_ID = v_parent_organisation_id,
							Inherit_Flg = p_inherit_flg, 
							Is_Skeleton = P_is_skeleton,
				  			Updated_Date = NOW(),
			          		Updated_by_User_ID = v_user_id,
			          		DB_Last_Updated_Date = NOW(),
			          		DB_Last_Updated_By = Current_User
			      WHERE Company_Name = p_company_name AND DB_Is_Deleted = FALSE;
			

			    ELSE
			      RAISE NOTICE 'Company % already exists and update is set to FALSE.', p_company_name;
			    END IF;
		
		ELSE
		    -- Insert new record
		    INSERT INTO Mgmt.Organisation (
		      Company_Name,
		      Company_Identifier,
		      Parent_Organisation_ID,
		      Inherit_Flg,
		      Created_By_User_ID	    )
		    VALUES (
		      p_company_name,
		      p_company_identifier,
		      v_parent_organisation_id,
		      p_inherit_flg,
		      v_user_id	    );
	 	END IF;
	END;
$BODY$
;








/* Create App_User Table */

CREATE SEQUENCE Mgmt.seq_App_User_ID
	START WITH 1
	INCREMENT BY 1
	NO MINVALUE
	NO MAXVALUE
	CACHE 1;



CREATE TABLE Mgmt.App_User
(
  App_User_Record_ID bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  App_User_ID bigint NOT NULL DEFAULT nextval('Mgmt.seq_App_User_ID'),
  User_Name varchar(255) DEFAULT 'MISSING' NOT NULL,
  User_Email varchar(255) DEFAULT 'MISSING' NOT NULL,
  User_Created_Date timestamp DEFAULT NOW() NOT NULL,
  User_Modified_Date timestamp DEFAULT NOW() NOT NULL,
  User_Last_Access_Date timestamp DEFAULT '1999-01-01 00:00:01.000' NULL,
  User_Cred_SO varchar(255) DEFAULT 'MISSING',
  User_Password varchar(768),
  Login_Allowed boolean DEFAULT True,
  Last_Modified_By bigint DEFAULT 1 NOT NULL,
  Is_Current boolean DEFAULT True ,
  DB_Created_Date     	TIMESTAMP WITH TIME ZONE  NULL  DEFAULT  NOW(),
  DB_Created_By        	VARCHAR(255)              NULL	DEFAULT  Current_User,
  DB_Is_Deleted         BOOLEAN                   NULL 	DEFAULT  FALSE,
  DB_Last_Updated_Date  TIMESTAMP WITH TIME ZONE  NULL 	DEFAULT  NOW(),
  DB_Last_Updated_By   	VARCHAR(255)              NULL 	DEFAULT  Current_User,
  Constraint "App_User_ID" PRIMARY KEY (App_User_ID)
)
;

/* Insert Skeleton Admin User */
INSERT INTO Mgmt.App_User	(user_name) 
VALUES ('Administrator1');



/* Additional Constraints */
CREATE UNIQUE INDEX IX_User_Name_Current on Mgmt.App_User (User_Name) WHERE Is_Current = TRUE;

/* Add Organisation <-> App_User FKs */
ALTER TABLE Mgmt.Organisation ADD CONSTRAINT FK_Organisation__App_User
  FOREIGN KEY (Created_By_User_ID) REFERENCES Mgmt.App_User (App_User_ID);

ALTER TABLE Mgmt.Organisation ADD CONSTRAINT FK_Organisation__App_User2
  FOREIGN KEY (Updated_by_User_ID) REFERENCES Mgmt.App_User (App_User_ID);


/* Comments */
COMMENT ON COLUMN Mgmt.App_User.User_Cred_SO IS E'Used to hold secondary credential ID (but not password) for a secret manager / SSO provider.';
COMMENT ON COLUMN Mgmt.App_User.User_Password IS E'NOT IN USE\nPlaceholder for user passwords if not managed at DB level. Passwords should be salted and hashed on entry.';
COMMENT ON COLUMN Mgmt.App_User.Login_Allowed IS E'NOT IN USE\nCould be used to prevent user login without removing from system. Never remove user ids';
COMMENT ON COLUMN Mgmt.App_User.Last_Modified_By IS E'Captures Users acting on other User accounts - e.g. administrators';














/* WIP!! */

CREATE TABLE Mgmt.LookUps
( 
	LookUp_ID              	BIGINT GENERATED ALWAYS AS IDENTITY,
	Organisation_ID			INT 		 NOT NULL 		DEFAULT 1, 
	LookUp_Name            	VARCHAR(50)  NOT NULL ,
	LookUp_Record_ID       	INT  NOT NULL ,
	LookUp_Value         	VARCHAR(255)  NOT NULL 		DEFAULT  'MISSING',
	Is_Current			   	BOOLEAN							DEFAULT  TRUE,
	Version_Key		     	INT NULL						DEFAULT  1,
	Note				   	VARCHAR(768) NULL			DEFAULT  'MISSING', 
	Display_Order       	INT 		NULL, 
	Ref_Entity				VARCHAR(255)	NULL			DEFAULT  'MISSING', 
	Created_By_User_ID		BIGINT NOT NULL 			DEFAULT 1,
	Replaced_By_User_ID		BIGINT NOT NULL 			DEFAULT 1,
	Valid_From		   		TIMESTAMP NOT NULL		    DEFAULT NOW(),
	Valid_To		  		TIMESTAMP NOT NULL			DEFAULT  '9999-12-31 23:59:59',
	Is_Skeleton		  		BOOLEAN						DEFAULT 	TRUE,
   	DB_Created_Date     	TIMESTAMP WITH TIME ZONE  NULL  DEFAULT  NOW(),
   	DB_Created_By        	VARCHAR(255)              NULL	DEFAULT  Current_User,
   	DB_Is_Deleted         	BOOLEAN                   NULL 	DEFAULT  FALSE,
   	DB_Last_Updated_Date  	TIMESTAMP WITH TIME ZONE  NULL 	DEFAULT  NOW(),
   	DB_Last_Updated_By   	VARCHAR(255)              NULL 	DEFAULT  Current_User,
	Constraint "LookUp_ID" PRIMARY KEY (LookUp_ID)
);



/* Constaints - Organisation_ID  and App_User_ID */
ALTER TABLE Mgmt.LookUps ADD CONSTRAINT FK_LookUps__App_User
  FOREIGN KEY (Created_By_User_ID) REFERENCES Mgmt.App_User (App_User_ID);

ALTER TABLE Mgmt.LookUps ADD CONSTRAINT FK_LookUps__App_User2
  FOREIGN KEY (Replaced_By_User_ID) REFERENCES Mgmt.App_User (App_User_ID);


ALTER TABLE Mgmt.LookUps ADD CONSTRAINT FK_LookUps__Organisation
  FOREIGN KEY (Organisation_ID) REFERENCES Mgmt.Organisation (Organisation_ID);


/* Records Table Creation against skeleton Org and with Admin user */
INSERT INTO Mgmt.LookUps(
	 organisation_id, lookup_name, lookup_record_id, lookup_value,  version_key, note, display_order, is_skeleton)
	VALUES (1, 'Creation_Note', 1,'Creation' , 1, 'Marks Table Creation', 1, TRUE);






/** General Consumption View************************************************************\
|	Allows any entity to be viewed, but excludes: 										|
|		* DB_Is_Deleted = 1																|
|	Generally most useful for a reporting layer											|
|		History filter (e.g. Is-Current) = True NOT Applied								|
\***************************************************************************************/ 


CREATE VIEW Mgmt.vw_LookUps as
(SELECT 		LookUp_ID, 
				Organisation_ID,	
				LookUp_Name,
				LookUp_Record_ID,
				LookUp_Value,
				Is_Current,	
				Version_Key,
				Note,
				Ref_Entity,
				Valid_From,
				Valid_To
				Is_Skeleton	
FROM 		Mgmt.LookUps
WHERE  		DB_Is_Deleted is false
AND LookUp_Record_ID > 0 -- skips the Lookup Creation Record
);



/** Create Entity **********************************************************************\
| An Entity is the container for any values. 											|
|																						|
| An Entity is always created with a sekelton record to capture Entity creation and to 	|
|	be its own sekelton 																|
|																						|
\***************************************************************************************/ 


-- PROCEDURE: mgmt.Create_LookUp(character varying[])
CREATE OR REPLACE PROCEDURE Mgmt.sp_Create_LookUp(
	IN p_LookUp_Name VARCHAR(50),
	IN p_App_User_ID BIGINT,
	IN p_Organisation_ID INT DEFAULT 1,
	IN p_Ref_Entity VARCHAR(255) DEFAULT 'MISSING'
)
LANGUAGE plpgsql
AS $$
DECLARE
	v_LookUp_Record_ID INT;
	v_User_Exists BOOLEAN;
	v_Name_Exists BOOLEAN;
BEGIN
	-- Check if the App_User_ID exists in the Mgmt.App_User table
	SELECT EXISTS(SELECT 1 FROM Mgmt.App_User WHERE App_User_ID = p_App_User_ID)
	INTO v_User_Exists;

	IF NOT v_User_Exists THEN
		RAISE EXCEPTION 'App_User_ID % does not exist in Mgmt.App_User table', p_App_User_ID;
	END IF;

	-- Check if the LookUp_Name already exists in the Mgmt.LookUps table
	SELECT EXISTS(SELECT 1 FROM Mgmt.LookUps WHERE LookUp_Name = p_LookUp_Name)
	INTO v_Name_Exists;

	IF v_Name_Exists THEN
		RAISE EXCEPTION 'LookUp_Name % already exists in Mgmt.LookUps table', p_LookUp_Name;
	END IF;


	-- Generate a new LookUp_Record_ID based on the max value for the given LookUp_Name
	SELECT COALESCE(MAX(LookUp_Record_ID), 0) + 1
	INTO v_LookUp_Record_ID
	FROM Mgmt.LookUps
	WHERE LookUp_Name = p_LookUp_Name;


	INSERT INTO Mgmt.LookUps (
					LookUp_Name,
					LookUp_Record_ID ,
					LookUp_Value,
					Ref_Entity,
					Created_By_User_ID,
					Organisation_ID
				)

				VALUES (
					p_LookUp_Name,
					0, -- zero captures lookup creation
					concat(p_LookUp_Name, ' - Creation'),
					p_Ref_Entity,
					p_App_User_ID,
					p_Organisation_ID 
					);

				-- Dynamically create a view using the provided LookUp_Name
				EXECUTE format('
					CREATE OR REPLACE VIEW Mgmt.%I AS
					SELECT 
						LookUp_ID,
						Organisation_ID,
						LookUp_Name,
						LookUp_Record_ID,
						LookUp_Value,
						Is_Current,
						Version_Key,
						Note,
						Ref_Entity,
						Valid_From,
						Valid_To,
						Is_Skeleton
					FROM Mgmt.LookUps
					WHERE LookUp_Name = %L
						AND DB_Is_Deleted = FALSE;',
					concat('vw_LU_',p_LookUp_Name), p_LookUp_Name);

END;
$$;


COMMENT ON PROCEDURE mgmt.sp_Create_LookUp
    IS 'Logical LookUp Creation.';

-- Next - add or update values to an existing lookup, with input arrays/*******************************************************************\
| 	Environment Entity is an example of holding an entity in 		|
|		LookUps Table												|
\*******************************************************************/


INSERT INTO mgmt.lookups(
	organisation_id, lookup_name, lookup_record_id, lookup_value, is_current, version_key, display_order, ref_entity)
	VALUES	
(1,'Environment',1,'Production',TRUE,1,1,'Environment'),
(1,'Environment',2,'Pre_Prod',TRUE,1,2,'Environment'),
(1,'Environment',3,'UAT',TRUE,1,3,'Environment'),
(1,'Environment',4,'SIT',TRUE,1,4,'Environment'),
(1,'Environment',5,'DEV',TRUE,1,5,'Environment');	



CREATE VIEW Mgmt.vw_Environment as
(SELECT 		LookUp_ID, 
				Organisation_ID,	
				LookUp_Name,
				LookUp_Record_ID,
				LookUp_Value,
				Is_Current,	
				Version_Key,
				Note,
				Ref_Entity,
				Valid_From,
				Valid_To
				Is_Skeleton	
FROM 		Mgmt.LookUps
WHERE  		DB_Is_Deleted is false
AND LookUp_Name = 'Environment'
AND Is_Current is True
);


INSERT INTO mgmt.lookups(
	organisation_id, lookup_name, lookup_record_id, lookup_value, is_current, version_key, note, display_order)
	VALUES	
(1,'File_Type',1,'csv',TRUE,1,'',1),
(1,'File_Type',2,'xls',TRUE,1,'Excel to 2003',2),
(1,'File_Type',3,'xlsx',TRUE,1,'Excel 2007 onwards',3),
(1,'File_Type',4,'xlsm',TRUE,1,'',4),
(1,'File_Type',5,'tsv',TRUE,1,'',5),
(1,'File_Type',6,'txt',TRUE,1,'',6);



CREATE VIEW Mgmt.vw_File_Type as
(SELECT 		LookUp_ID, 
				Organisation_ID,	
				LookUp_Name,
				LookUp_Record_ID,
				LookUp_Value,
				Is_Current,	
				Version_Key,
				Note,
				Ref_Entity,
				Valid_From,
				Valid_To
				Is_Skeleton	
FROM 		Mgmt.LookUps
WHERE  		DB_Is_Deleted is false
AND LookUp_Name = 'File_Type'
AND Is_Current is True
)/***************************************************************************************\
| Table: Country                                                                        |
| Based on ISO 3166-1                                                                   |                           
|       https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes                    |
|                                                                                       |
\***************************************************************************************/

Drop Table Mgmt.Country;

CREATE TABLE Mgmt.Country
(
  Country_ID integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  Country_Name varchar(255) DEFAULT 'Missing' NOT NULL,
  A2_Country_Code char(2) DEFAULT 'xx' NOT NULL,
  A3_Country_Code char(3) DEFAULT 'xxx' NOT NULL,
  Num_Country_Code char(3) DEFAULT '000' NOT NULL, 
  App_Country_Name varchar(255) DEFAULT 'Missing' NOT NULL,
  Is_Available BOOLEAN NOT NULL DEFAULT TRUE,
  App_Listing_Order INTEGER NOT NULL DEFAULT 9999,
  -- this is defined as a char to preserve leading zeros
  DB_Created_Date     	TIMESTAMP WITH TIME ZONE  NULL  DEFAULT  NOW(),
  DB_Created_By        	VARCHAR(255)              NULL	DEFAULT  Current_User,
  DB_Is_Deleted         BOOLEAN                   NULL 	DEFAULT  FALSE,
  DB_Last_Updated_Date  TIMESTAMP WITH TIME ZONE  NULL 	DEFAULT  NOW(),
  DB_Last_Updated_By   	VARCHAR(255)              NULL 	DEFAULT  Current_User,
PRIMARY KEY (Country_ID)
);


COMMENT ON COLUMN Mgmt.Country.Country_Name IS E'ISO-3166 Name';


CREATE UNIQUE INDEX IX_a3_Country_Code_Current on Mgmt.Country ( Country_Name) WHERE DB_Is_Deleted = False;



-- Create Reader View
CREATE VIEW Mgmt.vw_Country as
SELECT 
    Country_ID,
    case when App_Country_Name <> 'Missing' then App_Country_Name else Country_Name end as Diaplay_Country_Name,
    Country_Name,
    A2_Country_Code,
    A3_Country_Code,
    Num_Country_Code
from Mgmt.Country	
where  Is_Available = True 
and DB_Is_Deleted = False
Order by App_Listing_Order, Num_Country_Code;




-- Insert Skeleton Record
Insert into Mgmt.Country (Country_Name, A2_Country_Code, A3_Country_Code, Num_Country_Code)
Values ('Missing', 'xx', 'xxx', '000');


-- Insert those with a preferred app_country_name and/or listing order - e.g. UK, USA, etc.
Insert into Mgmt.Country (Country_Name, A2_Country_Code, A3_Country_Code, Num_Country_Code, App_Country_Name, Is_Available, App_Listing_Order)
Values      ('United Kingdom of Great Britain and Northern Ireland', 'GB', 'GBR', '826', 'UK', TRUE, 1),
            ('United States of America', 'US', 'USA', '840', 'USA', True, 2);


-- Insert rest of Current Iso-3166 Records: 
Insert into Mgmt.Country (Country_Name, A2_Country_Code, A3_Country_Code, Num_Country_Code)
Values ('Afghanistan', 'AF', 'AFG', '004'),
    ('Albania', 'AL', 'ALB', '008'),
    ('Algeria', 'DZ', 'DZA', '012'),
    ('Andorra', 'AD', 'AND', '020'),
    ('Angola', 'AO', 'AGO', '024'),
    ('Antigua and Barbuda', 'AG', 'ATG', '028'),
    ('Argentina', 'AR', 'ARG', '032'),
    ('Armenia', 'AM', 'ARM', '051'),
    ('Australia', 'AU', 'AUS', '036'),
    ('Austria', 'AT', 'AUT', '040'),
    ('Azerbaijan', 'AZ', 'AZE', '031'),
    ('Bahamas', 'BS', 'BHS', '044'),
    ('Bahrain', 'BH', 'BHR', '048'),
    ('Bangladesh', 'BD', 'BGD', '050'),
    ('Barbados', 'BB', 'BRB', '052'),
    ('Belarus', 'BY', 'BLR', '112'),
    ('Belgium', 'BE', 'BEL', '056'),
    ('Belize', 'BZ', 'BLZ', '084'),
    ('Benin', 'BJ', 'BEN', '204'),
    ('Bhutan', 'BT', 'BTN', '064'),
    ('Bolivia', 'BO', 'BOL', '068'),
    ('Bosnia and Herzegovina', 'BA', 'BIH', '070'),
    ('Botswana', 'BW', 'BWA', '072'),
    ('Brazil', 'BR', 'BRA', '076'),
    ('Brunei Darussalam', 'BN', 'BRN', '096'),
    ('Bulgaria', 'BG', 'BGR', '100'),
    ('Burkina Faso', 'BF', 'BFA', '854'),
    ('Burundi', 'BI', 'BDI', '108'),
    ('Cabo Verde', 'CV', 'CPV', '132'),
    ('Cambodia', 'KH', 'KHM', '116'),
    ('Cameroon', 'CM', 'CMR', '120'),
    ('Canada', 'CA', 'CAN', '124'),
    ('Central African Republic', 'CF', 'CAF', '140'),
    ('Chad', 'TD', 'TCD', '148'),
    ('Chile', 'CL', 'CHL', '152'),
    ('China', 'CN', 'CHN', '156'),
    ('Colombia', 'CO', 'COL', '170'),
    ('Comoros', 'KM', 'COM', '174'),
    ('Congo', 'CG', 'COG', '178'),
    ('Congo, Democratic Republic of the', 'CD', 'COD', '180'),
    ('Costa Rica', 'CR', 'CRI', '188'),
    ('Croatia', 'HR', 'HRV', '191'),
    ('Cuba', 'CU', 'CUB', '192'),
    ('Cyprus', 'CY', 'CYP', '196'),
    ('Czech Republic', 'CZ', 'CZE', '203'),
    ('Denmark', 'DK', 'DNK', '208'),
    ('Djibouti', 'DJ', 'DJI', '262'),
    ('Dominica', 'DM', 'DMA', '212'),
    ('Dominican Republic', 'DO', 'DOM', '214'),
    ('Ecuador', 'EC', 'ECU', '218'),
    ('Egypt', 'EG', 'EGY', '818'),
    ('El Salvador', 'SV', 'SLV', '222'),
    ('Equatorial Guinea', 'GQ', 'GNQ', '226'),
    ('Eritrea', 'ER', 'ERI', '232'),
    ('Estonia', 'EE', 'EST', '233'),
    ('Eswatini', 'SZ', 'SWZ', '748'),
    ('Ethiopia', 'ET', 'ETH', '231'),
    ('Fiji', 'FJ', 'FJI', '242'),
    ('Finland', 'FI', 'FIN', '246'),
    ('France', 'FR', 'FRA', '250'),
    ('Gabon', 'GA', 'GAB', '266'),
    ('Gambia', 'GM', 'GMB', '270'),
    ('Georgia', 'GE', 'GEO', '268'),
    ('Germany', 'DE', 'DEU', '276'),
    ('Ghana', 'GH', 'GHA', '288'),
    ('Greece', 'GR', 'GRC', '300'),
    ('Grenada', 'GD', 'GRD', '308'),
    ('Guatemala', 'GT', 'GTM', '320'),
    ('Guinea', 'GN', 'GIN', '324'),
    ('Guinea-Bissau', 'GW', 'GNB', '624'),
    ('Guyana', 'GY', 'GUY', '328'),
    ('Haiti', 'HT', 'HTI', '332'),
    ('Honduras', 'HN', 'HND', '340'),
    ('Hungary', 'HU', 'HUN', '348'),
    ('Iceland', 'IS', 'ISL', '352'),
    ('India', 'IN', 'IND', '356'),
    ('Indonesia', 'ID', 'IDN', '360'),
    ('Iran, Islamic Republic of', 'IR', 'IRN', '364'),
    ('Iraq', 'IQ', 'IRQ', '368'),
    ('Ireland', 'IE', 'IRL', '372'),
    ('Israel', 'IL', 'ISR', '376'),
    ('Italy', 'IT', 'ITA', '380'),
    ('Jamaica', 'JM', 'JAM', '388'),
    ('Japan', 'JP', 'JPN', '392'),
    ('Jordan', 'JO', 'JOR', '400'),
    ('Kazakhstan', 'KZ', 'KAZ', '398'),
    ('Kenya', 'KE', 'KEN', '404'),
    ('Kiribati', 'KI', 'KIR', '296'),
    ('Korea, Democratic People\''s Republic of', 'KP', 'PRK', '408'),
    ('Korea, Republic of', 'KR', 'KOR', '410'),
    ('Kuwait', 'KW', 'KWT', '414'),
    ('Kyrgyzstan', 'KG', 'KGZ', '417'),
    ('Lao People\''s Democratic Republic', 'LA', 'LAO', '418'),
    ('Latvia', 'LV', 'LVA', '428'),
    ('Lebanon', 'LB', 'LBN', '422'),
    ('Lesotho', 'LS', 'LSO', '426'),
    ('Liberia', 'LR', 'LBR', '430'),
    ('Libya', 'LY', 'LBY', '434'),
    ('Liechtenstein', 'LI', 'LIE', '438'),
    ('Lithuania', 'LT', 'LTU', '440'),
    ('Luxembourg', 'LU', 'LUX', '442'),
    ('Madagascar', 'MG', 'MDG', '450'),
    ('Malawi', 'MW', 'MWI', '454'),
    ('Malaysia', 'MY', 'MYS', '458'),
    ('Maldives', 'MV', 'MDV', '462'),
    ('Mali', 'ML', 'MLI', '466'),
    ('Malta', 'MT', 'MLT', '470'),
    ('Marshall Islands', 'MH', 'MHL', '584'),
    ('Mauritania', 'MR', 'MRT', '478'),
    ('Mauritius', 'MU', 'MUS', '480'),
    ('Mexico', 'MX', 'MEX', '484'),
    ('Micronesia (Federated States of)', 'FM', 'FSM', '583'),
    ('Moldova, Republic of', 'MD', 'MDA', '498'),
    ('Monaco', 'MC', 'MCO', '492'),
    ('Mongolia', 'MN', 'MNG', '496'),
    ('Montenegro', 'ME', 'MNE', '499'),
    ('Morocco', 'MA', 'MAR', '504'),
    ('Mozambique', 'MZ', 'MOZ', '508'),
    ('Myanmar', 'MM', 'MMR', '104'),
    ('Namibia', 'NA', 'NAM', '516'),
    ('Nauru', 'NR', 'NRU', '520'),
    ('Nepal', 'NP', 'NPL', '524'),
    ('Netherlands', 'NL', 'NLD', '528'),
    ('New Zealand', 'NZ', 'NZL', '554'),
    ('Nicaragua', 'NI', 'NIC', '558'),
    ('Niger (the)', 'NE', 'NER', '562'),
    ('Nigeria', 'NG', 'NGA', '566'),
    ('North Macedonia', 'MK', 'MKD', '807'),
    ('Norway', 'NO', 'NOR', '578'),
    ('Oman', 'OM', 'OMN', '512'),
    ('Pakistan', 'PK', 'PAK', '586'),
    ('Palau', 'PW', 'PLW', '585'),
    ('Panama', 'PA', 'PAN', '591'),
    ('Papua New Guinea', 'PG', 'PNG', '598'),
    ('Paraguay', 'PY', 'PRY', '600'),
    ('Peru', 'PE', 'PER', '604'),
    ('Philippines', 'PH', 'PHL', '608'),
    ('Poland', 'PL', 'POL', '616'),
    ('Portugal', 'PT', 'PRT', '620'),
    ('Qatar', 'QA', 'QAT', '634'),
    ('Romania', 'RO', 'ROU', '642'),
    ('Russian Federation', 'RU', 'RUS', '643'),
    ('Rwanda', 'RW', 'RWA', '646'),
    ('Saint Kitts and Nevis', 'KN', 'KNA', '659'),
    ('Saint Lucia', 'LC', 'LCA', '662'),
    ('Saint Vincent and the Grenadines', 'VC', 'VCT', '670'),
    ('Samoa', 'WS', 'WSM', '882'),
    ('San Marino', 'SM', 'SMR', '674'),
    ('Sao Tome and Principe', 'ST', 'STP', '678'),
    ('Saudi Arabia', 'SA', 'SAU', '682'),
    ('Senegal', 'SN', 'SEN', '686'),
    ('Serbia', 'RS', 'SRB', '688'),
    ('Seychelles', 'SC', 'SYC', '690'),
    ('Sierra Leone', 'SL', 'SLE', '694'),
    ('Singapore', 'SG', 'SGP', '702'),
    ('Slovakia', 'SK', 'SVK', '703'),
    ('Slovenia', 'SI', 'SVN', '705'),
    ('Solomon Islands', 'SB', 'SLB', '090'),
    ('Somalia', 'SO', 'SOM', '706'),
    ('South Africa', 'ZA', 'ZAF', '710'),
    ('South Sudan', 'SS', 'SSD', '728'),
    ('Spain', 'ES', 'ESP', '724'),
    ('Sri Lanka', 'LK', 'LKA', '144'),
    ('Sudan', 'SD', 'SDN', '729'),
    ('Suriname', 'SR', 'SUR', '740'),
    ('Sweden', 'SE', 'SWE', '752'),
    ('Switzerland', 'CH', 'CHE', '756'),
    ('Syrian Arab Republic', 'SY', 'SYR', '760'),
    ('Tajikistan', 'TJ', 'TJK', '762'),
    ('Tanzania, United Republic of', 'TZ', 'TZA', '834'),
    ('Thailand', 'TH', 'THA', '764'),
    ('Timor-Leste', 'TL', 'TLS', '626'),
    ('Togo', 'TG', 'TGO', '768'),
    ('Tonga', 'TO', 'TON', '776'),
    ('Trinidad and Tobago', 'TT', 'TTO', '780'),
    ('Tunisia', 'TN', 'TUN', '788'),
    ('Turkey', 'TR', 'TUR', '792'),
    ('Turkmenistan', 'TM', 'TKM', '795'),
    ('Tuvalu', 'TV', 'TUV', '798'),
    ('Uganda', 'UG', 'UGA', '800'),
    ('Ukraine', 'UA', 'UKR', '804'),
    ('United Arab Emirates', 'AE', 'ARE', '784'),
    ('Uruguay', 'UY', 'URY', '858'),
    ('Uzbekistan', 'UZ', 'UZB', '860'),
    ('Vanuatu', 'VU', 'VUT', '548'),
    ('Venezuela (Bolivarian Republic of)', 'VE', 'VEN', '862'),
    ('Viet Nam', 'VN', 'VNM', '704'),
    ('Yemen', 'YE', 'YEM', '887'),
    ('Zambia', 'ZM', 'ZMB', '894'),
    ('Zimbabwe', 'ZW', 'ZWE', '716');
/*******************************************************************\
|                                                                   |   
|   Create currency table                                           |              
|   Populate with ISO Currency list                                 |                         
|   Create exchange rate table (with history)                       |
|   Populate with exchange rates at _____________                   |
|                                                                   |                      
\*******************************************************************/



-- Create currency table
CREATE TABLE Mgmt.Currency (
    Currency_ID             integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    ISO_Currency_Code       VARCHAR(3) NOT NULL,
    Internal_Currency_Code  VARCHAR(20) NOT NULL DEFAULT 'Not Used',
    ISO_Currency_Name       VARCHAR(255) NOT NULL,
    Is_Available          BOOLEAN NOT NULL DEFAULT TRUE,
    Is_Current              BOOLEAN NOT NULL DEFAULT TRUE,
    Created_By_User_ID		BIGINT NOT NULL 			DEFAULT 1,
    Replaced_By_User_ID		BIGINT NOT NULL 			DEFAULT 1,
	  Valid_From		   		  TIMESTAMP NOT NULL		    DEFAULT NOW(),
	  Valid_To		  		    TIMESTAMP NOT NULL			DEFAULT  '9999-12-31 23:59:59',
    Is_Skeleton		  		  BOOLEAN						DEFAULT  FALSE, -- defaulted to false to simplify buil insert
  DB_Created_Date     	TIMESTAMP WITH TIME ZONE  NULL  DEFAULT  NOW(),
  DB_Created_By        	VARCHAR(255)              NULL	DEFAULT  Current_User,
  DB_Is_Deleted         BOOLEAN                   NULL 	DEFAULT  FALSE,
  DB_Last_Updated_Date  TIMESTAMP WITH TIME ZONE  NULL 	DEFAULT  NOW(),
  DB_Last_Updated_By   	VARCHAR(255)              NULL 	DEFAULT  Current_User,
    Constraint "Currency_ID" PRIMARY KEY (Currency_ID)
);


COMMENT ON COLUMN Mgmt.Currency.Internal_Currency_Code IS E'Used where the ISO code has been replaced for internal use.';
COMMENT ON COLUMN Mgmt.Currency.Is_Available            IS E'Is_current shows whether this is the current record for this currency.';
COMMENT ON COLUMN Mgmt.Currency.Is_Available            IS E'Is_available allows pre-seeded lists to be suppressed in the application layer.';

ALTER TABLE Mgmt.Currency  ADD CONSTRAINT FK_Currency__Users
  FOREIGN KEY (Created_By_User_ID) REFERENCES Mgmt.App_User (App_User_ID);

ALTER TABLE Mgmt.Currency  ADD CONSTRAINT FK_Currency__Users2
  FOREIGN KEY (Replaced_By_User_ID) REFERENCES Mgmt.App_User (App_User_ID);


CREATE VIEW Mgmt.vw_Currency AS
SELECT 
    Currency_ID,
    ISO_Currency_Code,
    Internal_Currency_Code,
    ISO_Currency_Name
FROM Mgmt.Currency
WHERE       Is_Current = TRUE
AND         Is_Available = TRUE
AND         DB_Is_Deleted = FALSE;


/* Created by Co-Pilot - not bad. Automatically picked up the Type 2 behaviour ****\

Had to add the DB_Last_Updated_By and DB_Last_Updated_Date fields to the Proc

 */

CREATE OR REPLACE PROCEDURE Mgmt.Add_Currency(
    p_ISO_Currency_Code VARCHAR(3),
    p_ISO_Currency_Name VARCHAR(255),
    p_Internal_Currency_Code VARCHAR(20) DEFAULT 'Not Used',
    p_Update BOOLEAN DEFAULT FALSE
)
LANGUAGE plpgsql
AS $$
BEGIN
    IF EXISTS (SELECT 1 FROM Mgmt.Currency WHERE ISO_Currency_Code = p_ISO_Currency_Code AND Is_Current = TRUE AND DB_Is_Deleted = FALSE) THEN
        IF p_Update THEN
            UPDATE Mgmt.Currency
            SET Is_Current = FALSE,
                Valid_To = NOW(),
                DB_Is_Deleted = TRUE,
                DB_Last_Updated_Date = NOW(),
                DB_Last_Updated_By = Current_User
            WHERE ISO_Currency_Code = p_ISO_Currency_Code AND Is_Current = TRUE AND DB_Is_Deleted = FALSE;

            INSERT INTO Mgmt.Currency (ISO_Currency_Code, ISO_Currency_Name, Internal_Currency_Code)
            VALUES (p_ISO_Currency_Code, p_ISO_Currency_Name, p_Internal_Currency_Code);
        ELSE
            RAISE NOTICE 'Currency % already exists and update is set to FALSE.', p_ISO_Currency_Code;
        END IF;
    ELSE
        INSERT INTO Mgmt.Currency (ISO_Currency_Code, ISO_Currency_Name, Internal_Currency_Code)
        VALUES (p_ISO_Currency_Code, p_ISO_Currency_Name, p_Internal_Currency_Code);
    END IF;
END;
$$;






/*** Insert Statements ***/


Insert Into Mgmt.Currency (ISO_Currency_Code, ISO_Currency_Name, Is_Skeleton)
Values
('XXX','The codes assigned for transactions where no currency is involved', TRUE);

Insert Into Mgmt.Currency (ISO_Currency_Code, ISO_Currency_Name)
Values
('AUD', 'Australian Dollar'),
('USD', 'United States Dollar'),
('GBP', 'British Pound'),
('EUR', 'Euro'),
('NZD', 'New Zealand Dollar'),
('JPY', 'Japanese Yen'),
('CAD', 'Canadian Dollar'),
('CHF', 'Swiss Franc'),
('SGD', 'Singapore Dollar'),
('HKD', 'Hong Kong Dollar'),
('SEK', 'Swedish Krona'),
('NOK', 'Norwegian Krone'),
('DKK', 'Danish Krone'),
('ZAR', 'South African Rand'),
('INR', 'Indian Rupee'),
('CNY', 'Chinese Yuan'),
('THB', 'Thai Baht'),
('MYR', 'Malaysian Ringgit'),
('IDR', 'Indonesian Rupiah'),
('PHP', 'Philippine Peso'),
('KRW', 'South Korean Won'),
('VND', 'Vietnamese Dong'),
('TWD', 'Taiwan Dollar'),
('SAR', 'Saudi Riyal'),
('AED', 'United Arab Emirates Dirham'),
('QAR', 'Qatari Riyal'),
('OMR', 'Omani Rial'),
('KWD', 'Kuwaiti Dinar'),
('BHD', 'Bahraini Dinar'),
('JOD', 'Jordanian Dinar'),
('ILS', 'Israeli Shekel'),
('EGP', 'Egyptian Pound'),
('LKR', 'Sri Lankan Rupee'),
('PKR', 'Pakistani Rupee'),
('BDT', 'Bangladeshi Taka'),
('NPR', 'Nepalese Rupee'),
('MVR', 'Maldivian Rufiyaa'),
('MUR', 'Mauritian Rupee'),
('SCR', 'Seychellois Rupee'),
('KES', 'Kenyan Shilling'),
('UGX', 'Ugandan Shilling'),
('TZS', 'Tanzanian Shilling'),
('ZMW', 'Zambian Kwacha'),
('GHS', 'Ghanaian Cedi'),
('NGN', 'Nigerian Naira'),
('ZAR', 'South African Rand'),
('MAD', 'Moroccan Dirham'),
('DZD', 'Algerian Dinar'),
('TND', 'Tunisian Dinar'),
('LYD', 'Libyan Dinar');




/*******************************************************************\
|                                                                   |
|   Create exchange rate table, which holds the Indirect_Quote      |
|   for each currency pair.                                         |
|                                                                   |                                      
|   This means that value in the "Source" or currency can           |
|   be MULTIPLIED by the exchange rate to get the value in the      |
|   "Target" currency                                               |
|
\******************************************************************/



Create Table Mgmt.Exchange_Rates
(Exchange_Rate_ID        INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
Source_Currency_Code      VARCHAR(3) NOT NULL,  -- no default, should always be specified
Target_Currency_Code      VARCHAR(3) NOT NULL,  -- no default, should always be specified
Indirect_Quote            NUMERIC(20,10) NOT NULL,
Is_Current              BOOLEAN NOT NULL            DEFAULT TRUE,
Created_By_User_ID		BIGINT NOT NULL 			DEFAULT 1,
Replaced_By_User_ID		BIGINT NOT NULL 			DEFAULT 1,
Valid_From		   		TIMESTAMP NOT NULL		    DEFAULT NOW(),
Valid_To		  		TIMESTAMP NOT NULL			DEFAULT  '9999-12-31 23:59:59',
Is_Skeleton		  		BOOLEAN						DEFAULT  FALSE, -- defaulted to false to simplify buil insert
DB_Created_Date     	TIMESTAMP WITH TIME ZONE  NULL  DEFAULT  NOW(),
DB_Created_By        	VARCHAR(255)              NULL	DEFAULT  Current_User,
DB_Is_Deleted         BOOLEAN                   NULL 	DEFAULT  FALSE,
DB_Last_Updated_Date  TIMESTAMP WITH TIME ZONE  NULL 	DEFAULT  NOW(),
DB_Last_Updated_By   	VARCHAR(255)              NULL 	DEFAULT  Current_User,
Constraint "Exchange_Rate_ID" PRIMARY KEY (Exchange_Rate_ID)
);  



ALTER TABLE Mgmt.Exchange_Rates ADD CONSTRAINT FK_Exchange_Rate__Users
  FOREIGN KEY (Created_By_User_ID) REFERENCES Mgmt.App_User (App_User_ID);

ALTER TABLE Mgmt.Exchange_Rates ADD CONSTRAINT FK_Exchange_Rate__Users2
  FOREIGN KEY (Replaced_By_User_ID	) REFERENCES Mgmt.App_User (App_User_ID);



ALTER TABLE Mgmt.Exchange_Rates ADD CONSTRAINT FK_Exchange_Rate__Currency
  FOREIGN KEY (Source_Currency_Code ) REFERENCES Mgmt.Currency (ISO_Currency_Code);

ALTER TABLE Mgmt.Exchange_Rates ADD CONSTRAINT FK_Exchange_Rate__Currency2
  FOREIGN KEY (Target_Currency_Code) REFERENCES Mgmt.Currency (ISO_Currency_Code);  

-- Create the skeleton record
Insert Into Mgmt.Exchange_Rates (Source_Currency_Code, Target_Currency_Code, Indirect_Quote,    Is_Skeleton)
Values
('XXX','XXX', '1.00', TRUE);


/* Role Model */



CREATE TABLE Mgmt.Roles
(
  Role_ID integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  Role_Description varchar(2000) DEFAULT 'MISSING' NOT NULL,
  Role_Permissions varchar(2000) DEFAULT 'None' NOT NULL,
  Created_By_User_ID bigint DEFAULT 1 NOT NULL,
  Created_Date timestamp DEFAULT NOW() NOT NULL,
  Is_Current boolean DEFAULT TRUE NOT NULL,
  Updated_by_User_ID bigint DEFAULT 1 NOT NULL,
  Updated_Date timestamp DEFAULT '9999-12-31 23:59:59' NOT NULL,
  Is_Skeleton boolean DEFAULT FALSE NOT NULL,
  DB_Created_Date     	TIMESTAMP WITH TIME ZONE  NULL  DEFAULT  NOW(),
  DB_Created_By        	VARCHAR(255)              NULL	DEFAULT  Current_User,
  DB_Is_Deleted         BOOLEAN                   NULL 	DEFAULT  FALSE,
  DB_Last_Updated_Date  TIMESTAMP WITH TIME ZONE  NULL 	DEFAULT  NOW(),
  DB_Last_Updated_By   	VARCHAR(255)              NULL 	DEFAULT  Current_User,
  Constraint "Role_ID" PRIMARY KEY (Role_ID)
);

-- Insert Skeleton Role 
Insert into Mgmt.Roles (Role_Description, Role_Permissions, Created_By_User_ID, Is_Skeleton)
Values ('Default Role', 'None', 1, True);



CREATE TABLE Mgmt.User_Permissions
(
  Company_Users_ID bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  Organisation_ID integer DEFAULT 1 NOT NULL,
  App_User_ID bigint DEFAULT 1 NOT NULL,
  Role_ID integer DEFAULT 1 NOT NULL,
  DB_Created_Date     	TIMESTAMP WITH TIME ZONE  NULL  DEFAULT  NOW(),
  DB_Created_By        	VARCHAR(255)              NULL	DEFAULT  Current_User,
  DB_Is_Deleted         BOOLEAN                   NULL 	DEFAULT  FALSE,
  DB_Last_Updated_Date  TIMESTAMP WITH TIME ZONE  NULL 	DEFAULT  NOW(),
  DB_Last_Updated_By   	VARCHAR(255)              NULL 	DEFAULT  Current_User,
    Constraint "Company_Users_ID" PRIMARY KEY (Company_Users_ID)
);

-- Insert Skeleton User_Permissions
Insert into Mgmt.User_Permissions (Organisation_ID, App_User_ID, Role_ID) 
Values (1, 1, 1);


COMMENT ON TABLE Mgmt.User_Permissions IS E'A user can have more than one role, in more than one companies';



ALTER TABLE Mgmt.User_Permissions ADD CONSTRAINT FK_User_Permissions__Roles
  FOREIGN KEY (Role_ID) REFERENCES Mgmt.Roles (Role_ID);

ALTER TABLE Mgmt.User_Permissions ADD CONSTRAINT FK_User_Permissions__Organisation
  FOREIGN KEY (Organisation_ID) REFERENCES Mgmt.Organisation (Organisation_ID);

ALTER TABLE Mgmt.User_Permissions ADD CONSTRAINT FK_User_Permissions__Users
  FOREIGN KEY (App_User_ID) REFERENCES Mgmt.App_User (App_User_ID);



/* Physical S2T Model */

CREATE TABLE Mgmt.Connection_Type
(
  Conn_Type_ID integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  Connection_Type varchar(255),
  Driver varchar(255),
  Is_Supported boolean DEFAULT True NOT NULL,
  DB_Created_Date     	TIMESTAMP WITH TIME ZONE  NULL  DEFAULT  NOW(),
  DB_Created_By        	VARCHAR(255)              NULL	DEFAULT  Current_User,
  DB_Is_Deleted         BOOLEAN                   NULL 	DEFAULT  FALSE,
  DB_Last_Updated_Date  TIMESTAMP WITH TIME ZONE  NULL 	DEFAULT  NOW(),
  DB_Last_Updated_By   	VARCHAR(255)              NULL 	DEFAULT  Current_User,
      Constraint "Conn_Type_ID" PRIMARY KEY (Conn_Type_ID)
)
;

COMMENT ON TABLE Mgmt.Connection_Type IS E'List of Connection types supported - e.g. OCBD, JDBC, FTP, Fileshare\n\nThis is abstracted from Source Type to allow multiple different connection types to the same source platform - e.g. PostgresDB, which may vary depending on whether the target is local, cloud/RDS. \n\nThis will go to LOOKUP table. \n'
;




CREATE TABLE Mgmt.Source_Type
(
  Source_Type_ID bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  Source_Type_Short varchar(20) DEFAULT 'MISSING' NOT NULL,
  Source_Type varchar(768) DEFAULT 'MISSING' NOT NULL,
  Source_Version varchar(255) DEFAULT 'MISSING',
  Is_Supported  boolean DEFAULT False,
  Is_Skeleton   boolean DEFAULT False,
  Conn_Type_ID  integer,
  File_Type_ID  bigint,
  DB_Created_Date     	TIMESTAMP WITH TIME ZONE  NULL  DEFAULT  NOW(),
  DB_Created_By        	VARCHAR(255)              NULL	DEFAULT  Current_User,
  DB_Is_Deleted         BOOLEAN                   NULL 	DEFAULT  FALSE,
  DB_Last_Updated_Date  TIMESTAMP WITH TIME ZONE  NULL 	DEFAULT  NOW(),
  DB_Last_Updated_By   	VARCHAR(255)              NULL 	DEFAULT  Current_User,
    Constraint "Source_Type_ID" PRIMARY KEY (Source_Type_ID)
)
;

-- Insert Skeleton Source_Type
INSERT INTO Mgmt.Source_Type (Source_Type_Short, Source_Type, Is_Skeleton)
VALUES ('Default', 'Default Source Type', True);


COMMENT ON COLUMN Mgmt.Source_Type.Source_Version IS E'Version of the application - e.g. SQL Server 2016/2019/2022 or Postgres V15, V16 etc. \n\nFor excel files, indicate the file type - e.g. xls, xlsx, xlsm. \n';
COMMENT ON COLUMN Mgmt.Source_Type.Is_Supported IS E'Is this source type currently supported by this application. ';
COMMENT ON COLUMN Mgmt.Source_Type.File_Type_ID IS E'Nullable - only populate for files';





CREATE TABLE Mgmt.Compression_Algorithm
(
  Comp_Algo_ID integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  Compression_Name varchar(20) DEFAULT 'MISSING',
  Compression_Description varchar(200) DEFAULT 'MISSING',
      Constraint "Comp_Algo_ID" PRIMARY KEY (Comp_Algo_ID)
)
;

-- Insert Skeleton Compression_Algorithm
Insert into Mgmt.Compression_Algorithm (Compression_Name, Compression_Description) 
Values ('Unspecified', 'Unspecified');




CREATE TABLE Mgmt.Data_Sources
(
  Data_Source_ID bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  Source_Type_ID bigint NOT NULL,
  Source_URI varchar(2000) DEFAULT 'MISSING' NOT NULL,
  Source_Description varchar(2000) DEFAULT 'MISSING' NOT NULL,
  Env_ID integer DEFAULT 1 NOT NULL,
  Source_Is_File boolean DEFAULT True NOT NULL,
  File_Type varchar(20) DEFAULT 'MISSING',
  Line_Ending varchar(10),
  Field_Delimmiter char(10),
  Quote_Character varchar(10),
  Escape_Character varchar(10),
  Comp_Algo_ID integer,
  Rows_Skip integer DEFAULT 0,
  DB_Created_Date     	TIMESTAMP WITH TIME ZONE  NULL  DEFAULT  NOW(),
  DB_Created_By        	VARCHAR(255)              NULL	DEFAULT  Current_User,
  DB_Is_Deleted         BOOLEAN                   NULL 	DEFAULT  FALSE,
  DB_Last_Updated_Date  TIMESTAMP WITH TIME ZONE  NULL 	DEFAULT  NOW(),
  DB_Last_Updated_By   	VARCHAR(255)              NULL 	DEFAULT  Current_User,
);





COMMENT ON TABLE Mgmt.Data_Sources IS E'Holds specifics of each source.\n  \nNote that separation of Source_Type and Source allows for multiple instances of the same source type - e.g. multiple databases and/or servers. \n\nDatabase connections should be captured at the DATABASE level, including the server name, rather than server level. \n'
;


COMMENT ON COLUMN Mgmt.Data_Sources.Source_URI IS E'URI for source, e.g. \n\n* HTTPS address\n* Server + Database Name\n';
COMMENT ON COLUMN Mgmt.Data_Sources.Source_Description IS E'Description of source - e.g. Premium data from UAT';
COMMENT ON COLUMN Mgmt.Data_Sources.File_Type IS E'File extension\nShould not be null when Source_Is_File is true. ';
COMMENT ON COLUMN Mgmt.Data_Sources.Line_Ending IS E'How is a line ended? e.g. \nLF\nCR/LF\nThis could have values restricted \n';
COMMENT ON COLUMN Mgmt.Data_Sources.Comp_Algo_ID IS E'Nullable';


ALTER TABLE Mgmt.Data_Sources ADD CONSTRAINT Data_Source_ID
  PRIMARY KEY (Data_Source_ID);





CREATE TABLE Mgmt.Data_Object
(
  Data_Object_ID bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  Data_Object_Name varchar(768) DEFAULT 'MISSING',
  Data_Object_Description bigint,
  Source_ID bigint DEFAULT 1 NOT NULL,
  Created_By_ID bigint DEFAULT 1 NOT NULL,
  Object_Created_Date date DEFAULT NOW() NOT NULL,
  DB_Created_Date     	TIMESTAMP WITH TIME ZONE  NULL  DEFAULT  NOW(),
  DB_Created_By        	VARCHAR(255)              NULL	DEFAULT  Current_User,
  DB_Is_Deleted         BOOLEAN                   NULL 	DEFAULT  FALSE,
  DB_Last_Updated_Date  TIMESTAMP WITH TIME ZONE  NULL 	DEFAULT  NOW(),
  DB_Last_Updated_By   	VARCHAR(255)              NULL 	DEFAULT  Current_User,
)
;

COMMENT ON TABLE Mgmt.Data_Object IS E'Details of the specific object being referenced - e.g. a Table Name in a database, tab name in Excel';
COMMENT ON COLUMN Mgmt.Data_Object.Created_By_ID IS E'User who created this Object Version';


ALTER TABLE Mgmt.Data_Object ADD CONSTRAINT Object_ID
  PRIMARY KEY (Data_Object_ID);



CREATE TABLE Mgmt.Source_Fields
(
  Field_ID bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  Field_Name varchar(256) NOT NULL,
  Field_Description varchar(2000) DEFAULT 'MISSING' NOT NULL,
  Attribute_ID bigint DEFAULT 1 NOT NULL,
  Data_Object_ID bigint DEFAULT 1 NOT NULL,
  Created_By_ID bigint DEFAULT 1 NOT NULL,
  Addtl_Att_IDs bigint,
  DB_Created_Date     	TIMESTAMP WITH TIME ZONE  NULL  DEFAULT  NOW(),
  DB_Created_By        	VARCHAR(255)              NULL	DEFAULT  Current_User,
  DB_Is_Deleted         BOOLEAN                   NULL 	DEFAULT  FALSE,
  DB_Last_Updated_Date  TIMESTAMP WITH TIME ZONE  NULL 	DEFAULT  NOW(),
  DB_Last_Updated_By   	VARCHAR(255)              NULL 	DEFAULT  Current_User,
)
;

COMMENT ON TABLE Mgmt.Source_Fields IS E'Individual PHYSICAL fields/columns related to object versions. \nBridge Table\n\nAlso allows referencing to Logical Attributes. \nShould be expanded to capture history of description & attribute tags in the physical model. \n';
COMMENT ON COLUMN Mgmt.Source_Fields.Field_Name IS E'256 character limit as default - exceeds most paltforms: \n\nPostgresql: 63 \nSQL Server 2022: 128';
COMMENT ON COLUMN Mgmt.Source_Fields.Addtl_Att_IDs IS E'Holds second or additional glossary attributes as needed. ';


ALTER TABLE Mgmt.Source_Fields ADD CONSTRAINT Field_ID
  PRIMARY KEY (Field_ID);

ALTER TABLE Mgmt.Source_Fields ADD CONSTRAINT FK_Source_Fields__Data_Object
  FOREIGN KEY (Data_Object_ID) REFERENCES Mgmt.Data_Object (Data_Object_ID);



CREATE TABLE Mgmt.Object_Version
(
  Object_Version_ID bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  Object_ID bigint DEFAULT 1 NOT NULL,
  Version_Description varchar(2000) DEFAULT 'MISSING' NOT NULL,
  Version_ID bigint DEFAULT 1 NOT NULL,
  Version_Created_By_ID bigint DEFAULT 1 NOT NULL,
  Version_Created_Date date DEFAULT NOW() NOT NULL,
  Is_Current_Version boolean  DEFAULT True NOT NULL,
  DB_Created_Date     	TIMESTAMP WITH TIME ZONE  NULL  DEFAULT  NOW(),
  DB_Created_By        	VARCHAR(255)              NULL	DEFAULT  Current_User,
  DB_Is_Deleted         BOOLEAN                   NULL 	DEFAULT  FALSE,
  DB_Last_Updated_Date  TIMESTAMP WITH TIME ZONE  NULL 	DEFAULT  NOW(),
  DB_Last_Updated_By   	VARCHAR(255)              NULL 	DEFAULT  Current_User,
)
;


COMMENT ON COLUMN Mgmt.Object_Version.Version_ID IS E'Increments by 1 for each new object version.';

ALTER TABLE Mgmt.Object_Version ADD CONSTRAINT Object_Ver_ID
  PRIMARY KEY (Object_Version_ID);







CREATE TABLE Mgmt.Object_Schema
(
  Obj_Schema_ID bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  Object_Version_ID bigint DEFAULT 1 NOT NULL,
  Field_ID bigint DEFAULT 1 NOT NULL,
  DB_Created_Date     	TIMESTAMP WITH TIME ZONE  NULL  DEFAULT  NOW(),
  DB_Created_By        	VARCHAR(255)              NULL	DEFAULT  Current_User,
  DB_Is_Deleted         BOOLEAN                   NULL 	DEFAULT  FALSE,
  DB_Last_Updated_Date  TIMESTAMP WITH TIME ZONE  NULL 	DEFAULT  NOW(),
  DB_Last_Updated_By   	VARCHAR(255)              NULL 	DEFAULT  Current_User,
);

COMMENT ON TABLE Mgmt.Object_Schema IS E'Object Schema is the bridge between Object and fields, creating a new set of rows for each version of the object with 1 row per field per object version per field.\n\n  This bridge table only uses surrogate keys, and all fields sit on the Primary Index\n\n\n'
;

ALTER TABLE Mgmt.Object_Schema ADD CONSTRAINT Obj_Schema_ID
  PRIMARY KEY (Obj_Schema_ID);


ALTER TABLE Mgmt.Object_Schema ADD CONSTRAINT FK_Object_Schema__Object_Version
  FOREIGN KEY (Object_Version_ID) REFERENCES Mgmt.Object_Version (Object_Version_ID);





CREATE TABLE Mgmt.Dataset
(
  Dataset_ID                bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  Source_Object_Version_ID  bigint DEFAULT 1 NOT NULL,
  Target_Object_Version_ID  bigint DEFAULT 1 NOT NULL,
  Dataset_Created_Date      timestamp DEFAULT NOW() NOT NULL,
  Dataset_Created_By_ID     bigint DEFAULT 1 NOT NULL,
  Is_Deleted                boolean DEFAULT False NOT NULL,
  Dataset_Deleted_Date      timestamp  NULL,
  Dataset_Deleted_By_ID     bigint NULL ,
  DB_Created_Date     	    TIMESTAMP WITH TIME ZONE  NULL  DEFAULT  NOW(),
  DB_Created_By        	    VARCHAR(255)              NULL	DEFAULT  Current_User,
  DB_Is_Deleted             BOOLEAN                   NULL 	DEFAULT  FALSE,
  DB_Last_Updated_Date      TIMESTAMP WITH TIME ZONE  NULL 	DEFAULT  NOW(),
  DB_Last_Updated_By   	    VARCHAR(255)              NULL 	DEFAULT  Current_User,
)
;

COMMENT ON TABLE Mgmt.Dataset IS E'A dataset is created for each instance of reading a datasource. \n\nEach datasset supports a Source_Object_Version and a Target-Object_Version to identify the schemata used. A target does not need to be specified - it will inherit MISSING record if not specified to allow previewing and then choosing a target. \n\nDataset records can be logically deleted at application and database level, separately. Either delete will suppress the data from View \n';

ALTER TABLE Mgmt.Dataset ADD CONSTRAINT FK_Object_Version__Created_By
  FOREIGN KEY (Dataset_Created_By_ID) REFERENCES Mgmt.App_User (App_User_ID);

ALTER TABLE Mgmt.Dataset ADD CONSTRAINT Dataset_ID
  PRIMARY KEY (Dataset_ID);

ALTER TABLE Mgmt.Dataset ADD CONSTRAINT FK_Dataset__Tgt_Object_Version
  FOREIGN KEY (Target_Object_Version_ID) REFERENCES Mgmt.Object_Version (Object_Version_ID);

ALTER TABLE Mgmt.Dataset ADD CONSTRAINT FK_Dataset__Src_Object_Version
  FOREIGN KEY (Target_Object_Version_ID) REFERENCES Mgmt.Object_Version (Object_Version_ID);



/* Business Data Catalog */
CREATE TABLE Mgmt.Domain
(
  Domain_ID integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  Domain_Name varchar(200) DEFAULT 'MISSING' NOT NULL,
  Domain_Description varchar(2000) DEFAULT 'MISSING' NOT NULL,
  Created_By_ID bigint DEFAULT 1 NOT NULL,
  Owned_By_ID bigint DEFAULT 1 NOT NULL,
  Created_Date date DEFAULT NOW() NOT NULL,
  DB_Created_Date     	TIMESTAMP WITH TIME ZONE  NULL  DEFAULT  NOW(),
  DB_Created_By        	VARCHAR(255)              NULL	DEFAULT  Current_User,
  DB_Is_Deleted         BOOLEAN                   NULL 	DEFAULT  FALSE,
  DB_Last_Updated_Date  TIMESTAMP WITH TIME ZONE  NULL 	DEFAULT  NOW(),
  DB_Last_Updated_By   	VARCHAR(255)              NULL 	DEFAULT  Current_User,
);

ALTER TABLE Mgmt.Domain ADD CONSTRAINT Domain_ID
  PRIMARY KEY (Domain_ID);


CREATE TABLE Mgmt.Entities
(
  Entity_ID bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  Entity_Name varchar(255) NOT NULL,
  Entity_Description varchar(2000),
  Created_By_ID bigint DEFAULT 1 NOT NULL,
  Created_Date date DEFAULT NOW(),
  Domain_ID integer NOT NULL
);


COMMENT ON TABLE Mgmt.Entities IS E'Entities holds LOGICAL data entities - i.e. tied to business glossaries, not systems. ';

ALTER TABLE Mgmt.Entities ADD CONSTRAINT Entity_Id
  PRIMARY KEY (Entity_ID);

CREATE TABLE Mgmt.Attributes
(
  Attribute_ID bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  Attribute_Name varchar(256) DEFAULT 'MISSING',
  Attribute_Description varchar(2000),
  Created_By_ID bigint DEFAULT 1 NOT NULL,
  Created_Date date DEFAULT NOW(),
  URI varchar(2000) DEFAULT 'MISSING',
  Entity_ID bigint DEFAULT 1 NOT NULL,
  DB_Created_Date     	TIMESTAMP WITH TIME ZONE  NULL  DEFAULT  NOW(),
  DB_Created_By        	VARCHAR(255)              NULL	DEFAULT  Current_User,
  DB_Is_Deleted         BOOLEAN                   NULL 	DEFAULT  FALSE,
  DB_Last_Updated_Date  TIMESTAMP WITH TIME ZONE  NULL 	DEFAULT  NOW(),
  DB_Last_Updated_By   	VARCHAR(255)              NULL 	DEFAULT  Current_User,
)
;


COMMENT ON TABLE Mgmt.Attributes IS E'Captures LOGICAL attributes under logical entities.\nAttributes should be aligned to business glossary rather than source system field/column names. \n'
;
COMMENT ON COLUMN Mgmt.Attributes.URI IS E'External URI for futher information / source of definition';


ALTER TABLE Mgmt.Attributes ADD CONSTRAINT Att_ID
  PRIMARY KEY (Attribute_ID);


ALTER TABLE Mgmt.Attributes ADD CONSTRAINT FK_Attributes__Entities
  FOREIGN KEY (Entity_ID) REFERENCES Mgmt.Entities (Entity_ID);

ALTER TABLE Mgmt.Attributes ADD CONSTRAINT FK_Attributes__Users
  FOREIGN KEY (Created_By_ID) REFERENCES Mgmt.App_User (App_User_ID);
