name: Consolidate SQL Scripts

on:
  push:
    branches:
      - main
      - dev_branch

jobs:
  consolidate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Consolidate SQL scripts
      run: |
        mkdir -p PostgreSQL/Container/docker/postgres
        cat PostgreSQL/SQL_Scripts/* > PostgreSQL/Container/docker/postgres/002-init.sql

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add PostgreSQL/Container/docker/postgres/002-init.sql
        git commit -m 'Consolidate SQL scripts on commit to dev_branch or main'
        git push